- name: disable current nodejs
  ansible.builtin.command: dnf module disable nodejs -y
  
- name: enable nodejs:20 module 
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: install nodejs
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
  - nodejs
  - mysql

- name: create expense user 
  ansible.builtin.user:
    name: expense



- name: install nodejs dependies
  tags: 
    - deployment
  community.general.npm:
    path: /app/

- name: copy backend service
  ansible.builtin.template:      ##if we want we can refer the files also##
    src: backend.service.j2
    dest: /etc/systemd/system/backend.service

- name: install pip dependies
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
  - PyMySQL
  - cryptography

- name: adding mysql schema
  community.mysql.mysql_db:
    state: import
    name: all
    login_host: "{{ MYSQL_HOST }}"
    login_password: "{{ MYSQL_PASSWORD }}"
    login_user: "{{ MYSQL_USER }}"
    target: /app/schema/backend.sql

- name: start,enable and daemon reload backend
  tags:
  - deployment
  ansible.builtin.systemd_service:
    name: backend
    state: restarted
    enabled: true
    daemon_reload: true

      